const stockProducts = [
  {
    id: 1,
    category: "chords",
    type: "guitar",
    name: "guitar 1",
    description: "very good guitar",
    colorsAvailable: ["red", "blue", "black", "white"],
    unitPrice: 1500,
    stockAmount: 12,
  },
  {
    id: 2,
    category: "chords",
    type: "guitar",
    name: "guitar 2",
    description: "very good guitar",
    colorsAvailable: ["red", "blue", "black", "white"],
    unitPrice: 1500,
    stockAmount: 12,
  },
  {
    id: 3,
    category: "chords",
    type: "guitar",
    name: "guitar 3",
    description: "very good guitar",
    colorsAvailable: ["red", "blue", "black", "white"],
    unitPrice: 1500,
    stockAmount: 12,
  },
  {
    id: 4,
    category: "chords",
    type: "guitar",
    name: "guitar 4",
    description: "very good guitar",
    colorsAvailable: ["red", "blue", "black", "white"],
    unitPrice: 1500,
    stockAmount: 12,
  },
  {
    id: 5,
    category: "percution",
    type: "drums",
    name: "drums 1",
    description: "very good drums",
    colorsAvailable: ["red", "blue", "black", "white"],
    unitPrice: 1500,
    stockAmount: 12,
  },
  {
    id: 6,
    category: "percution",
    type: "drums",
    name: "drums 2",
    description: "very good drums",
    colorsAvailable: ["red", "blue", "black", "white"],
    unitPrice: 1500,
    stockAmount: 12,
  },
];

module.exports = stockProducts;
